const repeatActions = {
  SET_ACTION: 'REPEAT_SET_ACTON',
  REGISTER_ACTION: 'REPEAT_REGISTER_ACTION',
  UPDATE_FIELD: 'REPEAT_UPDATE_FIELD',
  MODIFY_INPUT: 'REPEAT_MODIFY_INPUT',
  RESET_ACTION: 'REPEAT_RESET_ACTION'
}
